preactjs/preset-vite

src/devtools.ts
src/utils.ts

This issue was caused by differences in path handling on windows. Rollup internally normalizes all paths to only have posix path separators `/` everywhere and merges subsequent seperators into one.
Due to that mismatch the entry path never matched rollup's id path leading to `preact/debug` to never be injected.
Fixes #6

Fix preact/debug not injected on windows

---

.prettierignore
README.md
demo/vite.config.ts
src/index.ts

Releasing this preset to the public sparked a discussions on how presets should be done in vite. Presumably we were the first project to do so.
It turns out that plugins can be an array of plugins. This makes the config more composable and we can avoid using a somewhat internal function to merge configs.
See this issue for more background: https://github.com/vitejs/vite/issues/2500

Switch from config factory function to array of plugins

---

src/devtools.ts

When building with the sourcemap option config enabled (`vite build --sourcemap`), this message comes up:
```
Sourcemap is likely to be incorrect: a plugin (preact:devtools) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
```
This is because rollup [transform hook](https://rollupjs.org/guide/en/#transformers) should not return an object when doesn't apply any transforms

Do not return code from transform when not transforming

---

src/devtools.ts
src/hook-names.ts

The `config.isProduction` seems like a more reliable way to detect whether the plugin should inject code that is only desirable during development. This way things like development builds can more easily be realized (although it is questionable how well this is supported by Vite itself). I also think it is simply a cleaner solution than comparing the subcommand used when running Vite.

Use isProduction to decide whether to enable development-only transforms

---

package.json
src/hook-names.ts
src/index.ts
tsconfig.esm.json
tsconfig.json

Since Vite templates use ESM, there is no reason for this module to stay in
CommonJS, or to provide a CJS and ESM interface. This only complicates things.
Fixes: https://github.com/preactjs/preset-vite/issues/11.
Closes: https://github.com/preactjs/preset-vite/pull/12.
I also confirm that I tested with the template https://github.com/vitejs/vite/tree/main/packages/create-vite/template-preact, and it works fine.

Migrate to ESM

---

package-lock.json
package.json
tools/postbuild.mjs
tsconfig.cjs.json
tsconfig.json

Support both CommonJS and ES Module entry points

---

src/devtools.ts
src/hook-names.ts
src/index.ts

I made this fix locally for the ESM build, thought I'd pass it on. The script in the `tools` directory isn't updating the `utils` import properly unless the `.js` extension is present.

fix: use .js extension when importing utils

---

package-lock.json
package.json
src/index.ts

Since prefresh injects references to DOM nodes, its important to be able to exclude it from running on web worker scripts. This change passes the existing include/exclude options to `@prefresh/vite`.

Pass include/exclude to prefresh

---

package-lock.json
package.json
src/index.ts

This PR adds the babel plugin to transpile jsx to `jsxDEV` calls. Noticed that we used the [wrong argument order](https://github.com/preactjs/preact/pull/3459) in Preact for that transform too.
Fixes #40

Use JSX dev runtime for development

---

README.md
src/index.ts

I currently ran into an issue that legacy-decorators are not supported (same as #43) and I fixed it by adding the `@babel/plugin-proposal-decorators` and `@babel/plugin-proposal-class-properties`.
Unfortunately I had to inject these plugins directly into the packages source code. So I thought it would be nice to have an option to change babel config in vites config file.

Add support for custom babel configuration

---

package.json
src/index.ts

preact provides `exports` field and `module` field so it worked without interop codes.
This PR removes them because it was causing issues with Vite v3.
fixes https://github.com/preactjs/preset-vite/issues/52
I tested with Vite (3.0.0-beta.1, 2.9.12) and preact (10.8.2, 10.7.0) with reproduction on https://github.com/preactjs/preset-vite/issues/49.

fix: support vite v3

---

package.json
src/index.ts

* see https://github.com/microsoft/TypeScript/issues/48845

add named export to improve `"module": "nodenext"` compatibility

---

src/devtools.ts
src/index.ts

Adding entries to `optimizeDeps` will prevent these happening and it will reduce start up time.
```text
[vite] ✨ new dependencies optimized: preact/debug, preact/jsx-dev-runtime
[vite] ✨ optimized dependencies changed. reloading
```
This PR adds `preact/jsx-dev-runtime`, `preact/debug`, `preact/devtools` to `optimizeDeps`.

perf: add entries to optimizeDeps

---

README.md

I think we forgot to mention that we set this alias by default; no need for users to do it themselves.

docs: Mention automatic aliasing as feature in ReadMe

---

README.md
src/index.ts

Add two top-level options to disable either Dev Tools or Prefresh.
Both are great tools, but I have a use-case where I only need the basic Preact compatibility layer without the extra features.

Provide options to disable devtools and prefresh

---

.github/workflows/main.yml
package-lock.json
package.json
test/build.test.mjs
test/dev.test.mjs
test/util.mjs

- Add some simple tests for the preset (can be expanded on in the future)
- Add a GH workflow to run the tests on PRs and push
- Update some dependencies (ran `npm audit fix`)

Add some simple tests and GH workflow

---

tsconfig.json

Vite's min Node version is 14 so we can ship higher level JS then TypeScript's default. I believe ES2019 is a safe version to use. I didn't thoroughly check if we could go higher.
Doing this means we no longer down compile async/await to TS's manual state machine and instead ship native async/await.

Upgrade TypeScript target to ES2019

---

package-lock.json
package.json

Hi, as explained in issue #68 when you go to use this plugin an error is thrown because there is no Vite 4 support declaration. I checked the various breaking changes of both Vite and Rollup and it seems that there are no changes to be made to this plugin. 
I also used the output on my project and everything worked.
closes #68

Update peerDependencies to support Vite 4

---

package-lock.json
package.json
src/index.ts

fixes https://github.com/preactjs/preset-vite/issues/77

upgrade dependencies and add new stage 3 explicitResourceManagement

---

.editorconfig

My defaults differ quite a bit from the style here, this helps keep the diff sane 😅
A bit different than [the "standard" config we have in core](https://github.com/preactjs/preact/blob/main/.editorconfig) but I think it matches the style here correctly.

chore: Add `.editorconfig`

---

package-lock.json
package.json

I tested this on Prefresh already, I have yet to fully test it with this project. I figured that creating the PR is already good to find typing issues.
Resolves #89

bump peerDeps for vite 5

---

demo/tsconfig.json
package-lock.json
package.json

- Adds `tsconfig.json` to `demo/`
- As we don't set (and can't, due to using `tsc` as the compilation method) the JSX config, TS will (correctly) trip up if you open the demo in an editor.
- Adds `preact` as a devDep
- Was just testing Vite 5 and had to use `--legacy-peer-deps` as I didn't want to fiddle with versions, but unfortunately Preact was only implicitly included because it's a peer dep. Should probably be a full dev dep.
- Prettifies `.json` on commit else my badly formatted changes to the `package.json` slip through :p

chore: Add demo `tsconfig.json`, prettifies `.json` on commit, add `preact` as a devDep

---

src/index.ts

Not that this is too heavy, but from my understanding, its only purpose is for the devtools integration and so it should be tied to the `devtoolsEnabled` option.

refactor: Disable `transform-hook-names` if devtools aren't enabled

---

README.md
demo/index.html
demo/public/local-fetch-test.txt
demo/src/components/LocalFetch.tsx
demo/src/index.tsx
demo/src/pages/Home/index.tsx
demo/vite.config.ts
package-lock.json
package.json
src/index.ts
src/prerender.js
src/prerender.ts
test/build.test.mjs

Largely mimics WMR's setup, as that was pretty slick, with a few minor changes:
- Can prerender into any template element, doesn't require `document.body`
- Will search for `prerender()` function in any script listed in input HTML doc, doesn't require a certain placement
- User can specify a prerender script through the plugin options instead, if they prefer/need to
- Regex is fun, but switched off the HTML regex shenanigans for a real html parser. I'm a buzzkill, I know.
Patches for Vite's preloader were all that was needed to get the bundles working in Node. [I've asked if they'd be willing to implement this upstream](https://github.com/vitejs/vite/issues/15369), but we'll see.

feat: prerender plugin

---

src/prerender.ts

Ensures `/about/we-are-using` and `/about/we-are-using/` match so the latter doesn't create a new output file, overwriting the first (but Rollup does have a helpful warning for when that happens, which is handy).

fix: Normalize URLs w/ trailing slashes

---

demo/src/components/LocalFetch.tsx
src/prerender.ts

feat: Return proper `Response` from patched `fetch` during prerender

---

demo/package.json
package-lock.json
package.json
src/prerender.ts

Closes #106 
Full example:
```bash
$ npm run build
> build
> vite build
vite v5.1.3 building for production...
✓ 19 modules transformed.
x Build failed in 316ms
error during build:
RollupError: [preact:prerender]
ReferenceError: document is not defined
This is most likely caused by using DOM/Web APIs which are not available
available to the prerendering process running in Node. Consider
wrapping the offending code in a window check like so:
if (typeof window !== "undefined") {
// do something in browsers only
}
> /home/ryun/Projects/my-preact-app/src/index.jsx:22:18
20 | }
21 |
> 22 | hydrate(<App />, document.getElementById('app'));
|                  ^
23 |
24 | export async function prerender(data) {
25 | 	return await ssr(<App {...data} />);
at getRollupEror …
```

Feat: Better prerender errors

---

src/prerender.ts

> Unfortunately there's no way for us to clean up the source maps, and we need to enable them for all users running the prerender. Vite doesn't add them to the bundle, so we can't simply delete them, and it looks like they're written post `writeBundle()`, leaving us without much in the way of options to clean up after ourselves. Even if we could find a way, Vite would still likely include them in the output message which would be a bit wonky if they were then to not be there.
- #107
Turns out this is incorrect, and in Vite v4.0.0+, source maps are available in the bundle (via `generateBundle()` &`writeBundle()`) AND no longer shown as separate assets in the output message, meaning they're easy to clean up and shouldn't be a source of confusion if they are stripped.
For context, here's the …

refactor: Clean sourcemaps in newer Vite versions

---

src/devtools.ts
src/index.ts

Non-breaking form of #112
`devToolsEnabled` becomes a derived value, formed of the user passed option, whether it's a prod build or not, and the user-passed `devtoolsInProd` option.
Still not sure about the devtools source, see below

fix: Devtool flag inconsistencies

---

src/index.ts

Called out by @ArnaudBarre a few months ago on the Vite Discord (if memory serves), cheers to him for spotting this

refactor: Use ESBuild in prod if a user does not require Babel

---

src/prerender.ts

Closes #115
`stack-trace` is shipped exclusively as ESM, so this switches to importing via dynamic import to fix CJS consumers.

fix: Ensure `stack-trace` works w/ CJS build

---

src/prerender.ts

Looks like I forgot to strip the sourcemap comments in addition to the sourcemap files.

fix: Ensure sourcemap comments are stripped too

---

src/prerender.ts

I must've made the (always foolish) decision to make a last-second edit before pushing 🤦
Alternatively could slide a `/m` flag in for the regex, but now that I see this again, I think cleaning up the extraneous newline is preferable?

fix: Sourcemap regex

---

package-lock.json
package.json

Fixes #121 
- added missing dependency on `@babel/code-frame`, which is used [here](https://github.com/preactjs/preset-vite/blob/main/src/prerender.ts#L7)

Add @babel/code-frame as a dependency

---

src/prerender.ts

Closes #125
Dynamic imports now result in something like this:
```js
(()=>import("./index-kayMhHeV.js"),__VITE_PRELOAD__)
```
Which then throws as Vite hasn't subbed it out.
It used to be a string like so:
```js
(()=>import("./index-kayMhHeV.js"),"__VITE_PRELOAD__")
```
for reasons even the Vite team wasn't clear on (see reference in change)

fix: Stub out `__VITE_PRELOAD__` during prerender

---

src/index.ts

Closes #128
The `.cjs` support is perhaps debatable, not sure if that's really an issue people will run into.

fix: Support `.cjs` & `.mjs` extensions

---

README.md
demo/vite.config.ts
package.json
src/index.ts
src/prerender.ts

As of v5, Vite's preview server will no longer make any attempt to serve anything but `/index.html` for any request missing a file extension -- `/foo` will not result in `/foo/index.html` being returned.
This tends to result in hydration mismatches that users might not expect or recognize; for example, in our demo here (which largely mirrors our template for `create-preact`) we assign an `active` class for items in the header to show which route is active. If the user loads `/404` in their browser, both the "Home" and "404" header items will have the `active` class. It's easy for users to confuse this as a hydration issue with Preact or Preact-ISO when the reality is that the wrong HTML file was returned. 
To fix this, we can add a simple middleware that converts `/foo` into …

feat: Add preview middleware for prerender plugin

---

package.json

Only saw when I went to publish, seems NPM prefers this form now:
```
npm warn publish npm auto-corrected some errors in your package.json when publishing.  Please run "npm pkg fix" to address these errors.
npm warn publish errors corrected:
npm warn publish "repository" was changed from a string to an object
npm warn publish "repository.url" was normalized to "git+https://github.com/preactjs/preset-vite.git"
```

chore: Fix `"repository"` field in pkg.json

---

src/index.ts

Closes #76
Corrects a rather bizarre HMR bug.
If the user doesn't directly import anything from `preact` (as our prerender templates do not, instead pulling `hydrate` from `preact-iso`), Vite won't optimize the `preact` dependency (or won't do so in the same way, anyhow) and prefresh will fail to reload any components altered in a module outside of the root (e.g., `/src/components/*`).
Not quite sure why this is yet, but always optimizing preact shouldn't be a problem -- it'll always exist somewhere in the user's app, even if not directly used. Optimizing it won't be a waste.

fix: Ensure `preact` is optimized by Vite

---

README.md
demo/src/index.tsx
src/prerender.ts
test/build.test.mjs

Same API we used for WMR.
I believe I skipped adding this originally as `preact-iso` was injecting its own script tag as a marker for hydration and I wasn't quite sure whether this should fall on the prerender plugin side of things or iso. I'm leaning towards the prerender plugin now (as shown by this PR), but can go either way.

feat: Prerender data API

---

package.json
tools/postbuild.mjs
tsconfig.cjs.json
tsconfig.json

Noticed that the types weren't found under ESM. TypeScript these days needs separate declaration files for ESM and CJS. With the help of https://arethetypeswrong.github.io/ the changes in this PR ensure that types can be found in all scenarios.
Fixes https://github.com/denoland/deno/issues/25529

fix: unable to find TS types under ESM

---

src/prerender.ts

`originalFetch`? `vanillaFetch`? `Fetch`? Naming is hard, certainly looking for better names if ya got 'em.
---
Current setup makes it a bit more verbose to provide your own fetch impl, as we override without providing any way for consumers to get the original. You'd have to add `globalThis.unpatchedFetch = globalThis.fetch;` into your Vite config file for later retrieval in your app, which isn't ideal.

refactor: Provide original, unpatched fetch impl on globalThis

---

package-lock.json
package.json

Bumps range for vite peer dependency to include new v6 version, no breaking changes required.
[Vite 5 to 6 migration/breaking changes](https://main.vitejs.dev/guide/migration)

feat: bump vite peer dep

---

src/prerender.ts
test/build.test.mjs

This has been a fairly long-standing issue in the prerenderer that I've unfortunately just not had the time to track down.
The issue is that Rollup/Vite notices both the web entry chunk & the prerender chunk (containing, at a realistic minimum, rts) both depend on a number of shared modules (`preact`, amongst others) and so it will extract out those shared modules to a separate chunk. This gives us an app entry module like the following:
```js
import '/index.hash123.js';
function modulePreloadPolyfill() { ... }
```
You can see this if you load up the Preact docs site, the first JS file that's downloaded is just a static import of our actual app & Vite's modulepreload polyfill -- not ideal.
Vite has always added a modulepreload link with the real bundle path, and with this entry being so …

refactor: Ensure module preload polyfill is inlined into main bundle

---

src/prerender.ts

Largely a sync from [`vite-prerender-plugin`](https://github.com/rschristian/vite-prerender-plugin) -- I'm thinking of moving that into the Preact org (as it's ~60% Preact code anyhow..) to ease maintenance a bit as this ain't great as-is. Could then make it an optional peer dep here (instead of essentially vendoring it), reducing install size for all who aren't using it. That repo has a test suite, not as good as it can be but better than here, which I'm not super excited about mirroring into this repo. Need to think about it anyhow.
Changes:
- Vite 6 disallows editing most config values from `resolvedConfig()`, instead, directing users to `config()` (they might've  hinted at this previously but it wasn't enforced). `manualChunks` is an exception though, can only be set from …

refactor: Fix source maps, error code frames, and other misc items

---

src/index.ts

Someone [mentioned this in Slack](https://preact.slack.com/archives/C3NMBSJKH/p1735560924649199) the other day. It appears as though any use of the `'use client'` directive w/ sourcemaps enabled will trigger this warning, and do so per file -- react query & MUI (apparently) result in a lot of terminal spam as such.
Reference:
- https://github.com/vitejs/vite-plugin-react/pull/369
- https://github.com/evanw/esbuild/issues/3548

refactor: Silence Rollup warnings regarding source maps & use directives

---

src/index.ts

The way dependencies work in Deno is that they must be reachable through the module graph. But because the way we loaded the babel plugins is not analysable, the dependencies weren't found.
This PR switches the old school dynamic string-based loading to standard ESM imports.
Fixes https://github.com/denoland/deno/issues/27432

fix: Support Deno

---

src/index.ts

In Astro if you use react and preact in the same project, setting `jsxImportSource` to preact causes things to fail. This PR makes it so that using babel will not set esbuild options

fix: do not set jsxImportSource when using babel

---

package-lock.json
package.json
src/devtools.ts

50kb vs 6kb in package size so that would be a 44kb reduction for us

Replaces kolorist with picocolors

---

package-lock.json
package.json

feat: support vite v7
